# Generated by Django 5.0 on 2025-12-26 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queues', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['company', 'position'], name='queues_company_d80a40_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['company', 'is_completed'], name='queues_company_11eb21_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['student', 'is_completed'], name='queues_student_fe5a83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('company', 'student')},
        ),
    ]
