# Generated by Django 5.0 on 2025-12-26 20:59

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('access_token', models.CharField(default=companies.models.generate_access_token, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting'), ('paused', 'Paused')], default='recruiting', max_length=12)),
                ('max_concurrent_interviews', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
    ]
