# Generated by Django 5.0 on 2025-12-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_queue_size',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
